#################################################################################
##注意事项：
##符号均使用英文符号，禁止中文符号
##“;”分号之后为注释内容
[Radar_Location]
0=HJZJ_FMR

[HJZJ_FMR]
Tx_ID = 0x7A4
Rx_ID = 0x7AC
Fun_ID= 0x7DF

[config]
AbitBaudRate=500000;               仲裁域波特率
DbitBaudRate=2000000;              数据域波特率
FrameType=1;                       0:CAN帧    1:CANFD帧
CanfdStandard=0;                   CANFD标准  0:CANFD ISO    1:CANFD BOSCH
FillByte=0x00;                     数据填充
FlowStatus=0x00;                   FS
BlockSize=0x00;                    BS
STmin=0x00;
p2can_server_max=500;              刷新诊断请求的响应超时最大时间(ms)
p2xcan_server_max=5000;            NRC78的超时判断最大时间(ms)
PeriodMsg=;			               周期唤醒报文(例:450 08 50 40 01 00 00 00 00 00) ID + dlc + data

[NRC]
0x7F107F = 
#################################################################################
## Bootload刷新配置，请按照项目刷新流程自行配置
## ";"分号后为注释内容
## [Start]									# 刷新流程入口，不可修改
## Start = Step01;							# 刷新步骤
## Delay = 10;                              # 全局默认发送一帧报文后的延时 
## 
## [Step]
## Notes =;						  			# 注释
## IsFunID=1;								# 是否使用[config]中的FUN_ID
## Tx=10 03;						        # 发送报文				
## Rx=50 03 00 32 01 F4;			        # 接收报文
## Delay = 1000;					        # 接收到正确响应报文后的延时(单位毫秒)
## TxAlgorithm =;					        # 算法拼接到Tx后
## RxAlgorithm =;					        # 算法拼接到Rx后
## Function =;						        # 上位机根据Function触发不同的操作
## NextStep = Step02;				        # 下一步

##刷新流程
[Start]
Start = Step01;
Delay = 100;全局默认发送一帧报文后的延时

[Step01]
Notes = -->Diagnostic Session Control – extended Diagnostic Session
Tx=10 03
Rx=50 03 00 32 01 F4
IsFunID = use;
NextStep = Step02

[Step02]
Notes = -->SecurityAccess
Tx=27 01
Rx=67 01
Function = SecurityAccess;安全访问
NextStep = Step03

[Step03]
Notes = -->SecurityAccess_Check
Tx=27 02
Rx=67 02
TxAlgorithm = FMR.dll
Function = SecurityAccessCheck;安全访问校验
NextStep = Step04

[Step04]
Notes = -->Check the pre-programmed conditions.
Tx=31 01 F0 02
Rx=71 01 F0 02 00
NextStep = Step05

[Step05]
Notes = -->Disable DTC
Tx=85 02
Rx=C5 02
IsFunID = use;
NextStep = Step06

[Step06]
Notes = -->Disable non-diagnostic communication
Tx=28 03 03
Rx=68
IsFunID = use;
NextStep = Step07

[Step07]
Notes = -->Diagnostic Session Control-programming Session
Tx=10 02
Rx=50 02 00 32 01 F4
Function = SecurityAccess;安全访问
NextStep = Step08

[Step08]
Notes = -->SecurityAccess_Check
Tx=27 03
Rx=67 03
Function = SecurityAccess;安全访问
NextStep = Step09

[Step09]
Notes = -->Write Data By Identifier-Write Fingerprint
Tx=27 04
Rx=67 04
TxAlgorithm = FMR.dll
Function = SecurityAccessCheck;安全访问校验
NextStep = Step10

[Step10]
Notes = -->Write Data By Identifier-Write Fingerprint
Tx=2E F1 84 11 22 33 44 55 66 77 88 99 AA
Rx=6E F1 84
NextStep = Step11

[Step11]
Notes = -->flash_driver_RequestDownload
Tx=34 00 44
Rx=74
Function = FlashDriver_RequestDownload
NextStep = Step12

[Step12]
Notes = -->TransferData
Tx=36
Rx=76
Function = FlashDriver_TransferData
NextStep = Step13

[Step13]
Notes = -->RequestTransferExit
Tx=37
Rx=77
Function = FlashDriver_RequestTransferExit;请求传输退出
NextStep = Step14

[Step14]
Notes = -->Routine Control-check FLASH Routine
Tx=31 01 F1 A0
Rx=71 01 F1 A0 00
TxAlgorithm = HJZJ_CRC32.dll
Function = FlashDriver_CheckFlash;安全签名验证
NextStep = Step15

[Step15]
Notes = -->ROUTINE_EraseMemory_StartRoutine
Tx=31 01 FF 00 44
Rx=71 01 FF 00 00
TxAlgorithm = EraseMemory.dll
Function = APP_EraseMemory;擦除内存
NextStep = Step16

[Step16]
Notes = -->APP-RequestDownload
Tx=34 00 44
Rx=74
TxAlgorithm =
Function = APP_RequestDownload;请求下载
NextStep = Step17

[Step17]
Notes = -->TransferData
Tx=36
Rx=76
Algorithm = 
Function = APP_TransferData;传输数据
NextStep = Step18

[Step18]
Notes = -->RequestTransferExit
Tx=37
Rx=77
Algorithm = 
Function = APP_RequestTransferExit;请求退出
NextStep = Step19

[Step19]
Notes = -->Routine Control-check APP Routine
Tx=31 01 F1 A0
Rx=71 01 F1 A0 00
TxAlgorithm = HJZJ_CRC32.dll
Function = App_CheckFlash;安全签名验证
NextStep = IsDownloadFileOk ? Step20 : Step15

[Step20]
Notes = -->Routine Control-CheckReprogrammingDependencies
Tx=31 01 FF 01
Rx=71 01 FF 01 00
NextStep = Step21

[Step21]
Notes = -->ECU Reset-HardReset
Tx=11 01
Rx=51 01
