if(NOT DEFINED UDS_SOURCE_DIR)
  message(FATAL_ERROR "UDS_SOURCE_DIR is required")
endif()

set(ROOT "${UDS_SOURCE_DIR}/third_party/vendor_reference/UDS_V3.0.2")
set(MANIFEST "${ROOT}/SOURCE_MANIFEST.sha256")
if(NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "Vendor reference manifest is missing")
endif()

file(READ "${MANIFEST}" MANIFEST_CONTENT)
string(REPLACE "\r\n" "\n" MANIFEST_CONTENT "${MANIFEST_CONTENT}")
string(REPLACE ";" "\\;" MANIFEST_CONTENT "${MANIFEST_CONTENT}")
string(REPLACE "\n" ";" ENTRIES "${MANIFEST_CONTENT}")
set(COUNT 0)
foreach(ENTRY IN LISTS ENTRIES)
  if(ENTRY MATCHES "^#" OR ENTRY STREQUAL "")
    continue()
  endif()
  string(REPLACE "|" ";" FIELDS "${ENTRY}")
  list(LENGTH FIELDS FIELD_COUNT)
  if(NOT FIELD_COUNT EQUAL 4)
    message(FATAL_ERROR "Malformed manifest entry: ${ENTRY}")
  endif()
  list(GET FIELDS 0 RELATIVE_PATH)
  list(GET FIELDS 1 EXPECTED_SIZE)
  list(GET FIELDS 2 EXPECTED_HASH)
  set(PATH "${ROOT}/${RELATIVE_PATH}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "Reference file missing: ${RELATIVE_PATH}")
  endif()
  file(SIZE "${PATH}" ACTUAL_SIZE)
  file(SHA256 "${PATH}" ACTUAL_HASH)
  string(TOLOWER "${ACTUAL_HASH}" ACTUAL_HASH)
  if(NOT ACTUAL_SIZE STREQUAL EXPECTED_SIZE OR
     NOT ACTUAL_HASH STREQUAL EXPECTED_HASH)
    message(FATAL_ERROR "Reference mismatch: ${RELATIVE_PATH}")
  endif()
  math(EXPR COUNT "${COUNT} + 1")
endforeach()

if(NOT COUNT EQUAL 68)
  message(FATAL_ERROR "Expected 68 source files, manifest has ${COUNT}")
endif()
message(STATUS "Vendor reference check: PASS (${COUNT} files)")
